# Dependencies
markdown:             kramdown
highlighter:          rouge


# Gems
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag


# Settings
exclude:              [CNAME, README.md, NOTES.md, LICENSE.md, .gitignore, package.json, bower.json, _js, _scss, _images, gulpfile.js, gulpconfig.js, node_modules, bower_components, gemfile, Gemfile.lock]
permalink:            /post/:title/
compress_html:
  clippings: all
  comments: all


# Site meta
title:                'Marc Reyes'
tagline:              'Blog'
description:          'Marc Reyes is a data-driven developer who is into studying AI and Machine Learning'
keywords:             'Marc Reyes, Marc, Reyes, Marc X, X, MX, M+X, Web Design, Website, Web Development, Web Dev, Freelancer, Speaking, Google, Google Developers, Code, Programming, Machine Learning'
url:                  https://www.marcreyes.ph
baseurl:              
assets:               /assets
images:               /images/
image:                /assets/images/1200x630-og-image.png
logo:                 /assets/icons/apple-icon-144x144.png
dark_theme:           true

author:
  name:               Marc Reyes
  bio:                Marc Reyes is a data-driven developer who is into studying AI and Machine Learning
  image:              author
  url:                https://blog.marcreyes.ph
  email:              hello@marcreyes.ph
  twitter:            marcreyesph

social:
  twitter:            https://twitter.com/marcreyesph
  instagram:          https://instagram.com/marcxplanet
  github:             https://github.com/marcreyesph
  medium:             https://medium.com/@marcreyesph

version:              3.1.3

github:
  repo:               https://github.com/marcreyesph


# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass:           400, 600, 800

google_analytics_key: UA-94021817-2
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM


# Content
excerpt_separator: <!-- Read more -->

navigation:
  GitHub: https://github.com/marcreyesph
